//! Calling conventions for Self's generated glue primitives.
//!
//! Produced from `objects/glue/*.primMaker.hh`, which is the table the
//! C++ VM builds its glue from: every entry gives the C function, its
//! return type and its argument types. Regenerate with
//! `scratchpad/gen_glue.py > src/glue_table.rs` if the world changes.

/// (primitive name, C function, return type, argument types)
pub const GLUE: &[(&str, &str, &str, &[&str])] = &[
    ("ATSFontFamilyFindFromName_wrapfindIDFromName", "ATSFontFamilyFindFromName_wrap", "unsigned_int", &["string_null"]),
    ("ATSFontFamilyGetName_wrapgetNameID", "ATSFontFamilyGetName_wrap", "oop", &["unsigned_int"]),
    ("ATSFontFamilyIteratorCreate_wrapcreateContextOptions:ResultProxy:", "ATSFontFamilyIteratorCreate_wrap", "proxy", &["unsigned_int", "unsigned_int"]),
    ("ATSFontFamilyIteratorNext_wrapnext", "ATSFontFamilyIteratorNext_wrap", "unsigned_int", &["proxy"]),
    ("ATSFontFamilyIteratorRelease_wraprelease", "ATSFontFamilyIteratorRelease_wrap", "specific_success_int", &["proxy"]),
    ("ATSFontFamilyIteratorReset_wrapresetContext:Options:", "ATSFontFamilyIteratorReset_wrap", "specific_success_int", &["proxy", "unsigned_int", "unsigned_int"]),
    ("ATSFontFindFromName_wrapfindIDFromName", "ATSFontFindFromName_wrap", "unsigned_int", &["string_null"]),
    ("ATSFontFindFromPostScriptName_wrapfindIDFromPostScriptName", "ATSFontFindFromPostScriptName_wrap", "unsigned_int", &["string_null"]),
    ("ATSFontGetHorizontalMetricsgetHorizontalMetricsIDOptions:Into:", "ATSFontGetHorizontalMetrics", "specific_success_int", &["unsigned_int", "unsigned_int", "proxy"]),
    ("ATSFontGetName_wrapgetNameID", "ATSFontGetName_wrap", "oop", &["unsigned_int"]),
    ("ATSFontGetPostScriptName_wrapgetPostScriptNameID", "ATSFontGetPostScriptName_wrap", "oop", &["unsigned_int"]),
    ("ATSFontGetVerticalMetricsgetVerticalMetricsIDOptions:Into:", "ATSFontGetVerticalMetrics", "specific_success_int", &["unsigned_int", "unsigned_int", "proxy"]),
    ("ATSFontIteratorCreate_wrapcreateContextOptions:ResultProxy:", "ATSFontIteratorCreate_wrap", "proxy", &["unsigned_int", "unsigned_int"]),
    ("ATSFontIteratorNext_wrapnext", "ATSFontIteratorNext_wrap", "unsigned_int", &["proxy"]),
    ("ATSFontIteratorRelease_wraprelease", "ATSFontIteratorRelease_wrap", "specific_success_int", &["proxy"]),
    ("ATSFontIteratorReset_wrapresetContext:Options:", "ATSFontIteratorReset_wrap", "specific_success_int", &["proxy", "unsigned_int", "unsigned_int"]),
    ("ATSTextLayoutSetContextsetContext:", "ATSTextLayoutSetContext", "specific_success_int", &["proxy", "proxy"]),
    ("ATSUCreateAndCopyStyle_wrapcreateAndCopyResultProxy:", "ATSUCreateAndCopyStyle_wrap", "proxy", &["proxy"]),
    ("ATSUCreateAndCopyTextLayout_wrapcreateAndCopyResultProxy:", "ATSUCreateAndCopyTextLayout_wrap", "proxy", &["proxy"]),
    ("ATSUCreateStyle_wrapcreateResultProxy", "ATSUCreateStyle_wrap", "proxy", &[]),
    ("ATSUCreateTextLayoutWithTextPtr_wrapcreateForStyleBytes:From:Size:ResultProxy:", "ATSUCreateTextLayoutWithTextPtr_wrap", "proxy", &["proxy", "cbv_len", "int", "int"]),
    ("ATSUCreateTextLayout_wrapcreateResultProxy", "ATSUCreateTextLayout_wrap", "proxy", &[]),
    ("ATSUDisposeStyledispose", "ATSUDisposeStyle", "specific_success_int", &["proxy"]),
    ("ATSUDisposeTextLayout_wrapdispose", "ATSUDisposeTextLayout_wrap", "specific_success_int", &["proxy"]),
    ("ATSUGetGlyphBounds_wrapraw_getGlyphBoundsAtX:Y:Start:Count:BoundsType:", "ATSUGetGlyphBounds_wrap", "oop", &["proxy", "float", "float", "int", "int", "unsigned_short"]),
    ("ATSUGetUnjustifiedBounds_wrapraw_getUnjustifiedBoundsStart:Count:", "ATSUGetUnjustifiedBounds_wrap", "oop", &["proxy", "int", "int"]),
    ("ATSUMeasureTextImage_wrapraw_measureTextImageStart:Count:", "ATSUMeasureTextImage_wrap", "oop", &["proxy", "int", "int"]),
    ("ATSUStyleSetFontIDAndSizesetFontID:Size:", "ATSUStyleSetFontIDAndSize", "specific_success_int", &["proxy", "unsigned_int", "float"]),
    ("ActivateWindowactivate:", "ActivateWindow", "specific_success_int", &["proxy", "bool"]),
    ("BlackPixelOfScreenblackPixelOfScreen", "BlackPixelOfScreen", "long", &["proxy"]),
    ("BringToFrontbringToFront", "BringToFront", "void", &["proxy"]),
    ("CFReleaserelease", "CFRelease", "void", &["proxy"]),
    ("CGCaptureAllDisplaysWithOptionscaptureAllOptions", "CGCaptureAllDisplaysWithOptions", "specific_success_int", &["unsigned_int"]),
    ("CGCaptureAllDisplayscaptureAll", "CGCaptureAllDisplays", "specific_success_int", &[]),
    ("CGColorSpaceCreateDeviceCMYKcreateDeviceCMYKResultProxy", "CGColorSpaceCreateDeviceCMYK", "proxy", &[]),
    ("CGColorSpaceCreateDeviceGraycreateDeviceGrayResultProxy", "CGColorSpaceCreateDeviceGray", "proxy", &[]),
    ("CGColorSpaceCreateDeviceRGBcreateDeviceRGBResultProxy", "CGColorSpaceCreateDeviceRGB", "proxy", &[]),
    ("CGColorSpaceCreateGenericCMYK_wrapcreateGenericCMYKResultProxy", "CGColorSpaceCreateGenericCMYK_wrap", "proxy", &[]),
    ("CGColorSpaceCreateGenericGray_wrapcreateGenericGrayResultProxy", "CGColorSpaceCreateGenericGray_wrap", "proxy", &[]),
    ("CGColorSpaceCreateGenericRGB_wrapcreateGenericRGBResultProxy", "CGColorSpaceCreateGenericRGB_wrap", "proxy", &[]),
    ("CGColorSpaceCreateIndexed_wrapcreateIndexedBasedOnColorTable:ResultProxy:", "CGColorSpaceCreateIndexed_wrap", "proxy", &["proxy", "cbv_len"]),
    ("CGColorSpaceCreatePatterncreatePatternResultProxy:", "CGColorSpaceCreatePattern", "proxy", &["proxy"]),
    ("CGColorSpaceGetNumberOfComponentsnumberOfComponents", "CGColorSpaceGetNumberOfComponents", "unsigned_int", &["proxy"]),
    ("CGColorSpaceGetTypeIDgetTypeID", "CGColorSpaceGetTypeID", "unsigned_int", &[]),
    ("CGColorSpaceReleaserelease", "CGColorSpaceRelease", "void", &["proxy"]),
    ("CGColorSpaceRetainretain", "CGColorSpaceRetain", "void", &["proxy"]),
    ("CGContextAddArcToPointaddArcToPointX1:Y1:X2:Y2:Radius:", "CGContextAddArcToPoint", "void", &["proxy", "float", "float", "float", "float", "float"]),
    ("CGContextAddArcaddArcX:Y:Radius:StartAngle:EndAngle:Clockwise:", "CGContextAddArc", "void", &["proxy", "float", "float", "float", "float", "float", "bool"]),
    ("CGContextAddCurveToPointaddCurveToPointCP1X:CP1Y:CP2X:CP2Y:X:Y:", "CGContextAddCurveToPoint", "void", &["proxy", "float", "float", "float", "float", "float", "float"]),
    ("CGContextAddEllipseInRect_wrapaddEllipseInRectX:Y:Width:Height:", "CGContextAddEllipseInRect_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextAddLineToPointaddLineToPointX:Y:", "CGContextAddLineToPoint", "void", &["proxy", "float", "float"]),
    ("CGContextAddPathaddPath:", "CGContextAddPath", "void", &["proxy", "proxy"]),
    ("CGContextAddQuadCurveToPointaddQuadCurveToPointCPX:CPY:X:Y:", "CGContextAddQuadCurveToPoint", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextAddRect_wrapaddRectX:Y:Width:Height:", "CGContextAddRect_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextBeginPathbeginPath", "CGContextBeginPath", "void", &["proxy"]),
    ("CGContextBeginTransparencyLayer_wrapbeginTransparencyLayer", "CGContextBeginTransparencyLayer_wrap", "void", &["proxy"]),
    ("CGContextClearRect_wrapclearRectX:Y:Width:Height:", "CGContextClearRect_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextClipToMask_wrapclipToX:Y:Width:Height:Mask:", "CGContextClipToMask_wrap", "void", &["proxy", "float", "float", "float", "float", "proxy"]),
    ("CGContextClipToRect_wrapclipToRectX:Y:Width:Height:", "CGContextClipToRect_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextClipclip", "CGContextClip", "void", &["proxy"]),
    ("CGContextClosePathclosePath", "CGContextClosePath", "void", &["proxy"]),
    ("CGContextConcatCTM_wrapconcatCTMMatrix_A:B:C:D:TX:TY:", "CGContextConcatCTM_wrap", "void", &["proxy", "float", "float", "float", "float", "float", "float"]),
    ("CGContextConvertPointToDeviceSpace_wrapraw_convertPointToDeviceSpaceX:Y:", "CGContextConvertPointToDeviceSpace_wrap", "oop", &["proxy", "float", "float"]),
    ("CGContextConvertPointToUserSpace_wrapraw_convertPointToUserSpaceX:Y:", "CGContextConvertPointToUserSpace_wrap", "oop", &["proxy", "float", "float"]),
    ("CGContextConvertRectToDeviceSpace_wrapraw_convertRectToDeviceSpaceX:Y:Width:Height:", "CGContextConvertRectToDeviceSpace_wrap", "oop", &["proxy", "float", "float", "float", "float"]),
    ("CGContextConvertRectToUserSpace_wrapraw_convertRectToUserSpaceX:Y:Width:Height:", "CGContextConvertRectToUserSpace_wrap", "oop", &["proxy", "float", "float", "float", "float"]),
    ("CGContextConvertSizeToDeviceSpace_wrapraw_convertSizeToDeviceSpaceWidth:Height:", "CGContextConvertSizeToDeviceSpace_wrap", "oop", &["proxy", "float", "float"]),
    ("CGContextConvertSizeToUserSpace_wrapraw_convertSizeToUserSpaceWidth:Height:", "CGContextConvertSizeToUserSpace_wrap", "oop", &["proxy", "float", "float"]),
    ("CGContextDrawImage_wrapdrawImage:X:Y:Width:Height:", "CGContextDrawImage_wrap", "void", &["proxy", "proxy", "float", "float", "float", "float"]),
    ("CGContextDrawLayerAtPoint_wrapdrawLayer:X:Y:", "CGContextDrawLayerAtPoint_wrap", "void", &["proxy", "proxy", "float", "float"]),
    ("CGContextDrawLayerInRect_wrapdrawLayer:X:Y:Width:Height:", "CGContextDrawLayerInRect_wrap", "void", &["proxy", "proxy", "float", "float", "float", "float"]),
    ("CGContextDrawPath_wrapdrawPathMode:", "CGContextDrawPath_wrap", "void", &["proxy", "int"]),
    ("CGContextDrawShadingdrawShading:", "CGContextDrawShading", "void", &["proxy", "proxy"]),
    ("CGContextEOClipeoClip", "CGContextEOClip", "void", &["proxy"]),
    ("CGContextEOFillPatheoFillPath", "CGContextEOFillPath", "void", &["proxy"]),
    ("CGContextEndTransparencyLayerendTransparencyLayer", "CGContextEndTransparencyLayer", "void", &["proxy"]),
    ("CGContextFillEllipseInRect_wrapfillEllipseX:Y:Width:Height:", "CGContextFillEllipseInRect_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextFillPathfillPath", "CGContextFillPath", "void", &["proxy"]),
    ("CGContextFillRect_wrapfillRectX:Y:Width:Height:", "CGContextFillRect_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextFlushflush", "CGContextFlush", "void", &["proxy"]),
    ("CGContextGetCTM_wrapraw_getCTM", "CGContextGetCTM_wrap", "oop", &["proxy"]),
    ("CGContextGetInterpolationQualityinterpolationQuality", "CGContextGetInterpolationQuality", "int", &["proxy"]),
    ("CGContextGetPathBoundingBox_wrapraw_getPathBoundingBox", "CGContextGetPathBoundingBox_wrap", "oop", &["proxy"]),
    ("CGContextGetPathCurrentPoint_wrapraw_getPathCurrentPoint", "CGContextGetPathCurrentPoint_wrap", "oop", &["proxy"]),
    ("CGContextGetTextMatrix_wrapraw_getTextMatrix", "CGContextGetTextMatrix_wrap", "oop", &["proxy"]),
    ("CGContextGetTextPosition_wrapraw_getTextPosition", "CGContextGetTextPosition_wrap", "oop", &["proxy"]),
    ("CGContextGetUserSpaceToDeviceSpaceTransform_wrapraw_getUserSpaceToDeviceSpaceTransform", "CGContextGetUserSpaceToDeviceSpaceTransform_wrap", "oop", &["proxy"]),
    ("CGContextIsPathEmptyisPathEmpty", "CGContextIsPathEmpty", "bool", &["proxy"]),
    ("CGContextMoveToPointmoveToPointX:Y:", "CGContextMoveToPoint", "void", &["proxy", "float", "float"]),
    ("CGContextPathContainsPoint_wrappathContainsPointX:Y:Mode:", "CGContextPathContainsPoint_wrap", "bool", &["proxy", "float", "float", "unsigned_int"]),
    ("CGContextReleaserelease", "CGContextRelease", "void", &["proxy"]),
    ("CGContextReplacePathWithStrokedPathreplacePathWithStrokedPath", "CGContextReplacePathWithStrokedPath", "void", &["proxy"]),
    ("CGContextRestoreGStaterestoreGState", "CGContextRestoreGState", "void", &["proxy"]),
    ("CGContextRetainretain", "CGContextRetain", "void", &["proxy"]),
    ("CGContextRotateCTMrotateCTM_Radians:", "CGContextRotateCTM", "void", &["proxy", "float"]),
    ("CGContextSaveGStatesaveGState", "CGContextSaveGState", "void", &["proxy"]),
    ("CGContextScaleCTMscaleCTM_X:Y:", "CGContextScaleCTM", "void", &["proxy", "float", "float"]),
    ("CGContextSelectFont_wrapselectFont:Size:", "CGContextSelectFont_wrap", "void", &["proxy", "string", "float"]),
    ("CGContextSetAllowsAntialiasingsetAllowsAntialiasing:", "CGContextSetAllowsAntialiasing", "void", &["proxy", "bool"]),
    ("CGContextSetAlphasetAlpha:", "CGContextSetAlpha", "void", &["proxy", "float"]),
    ("CGContextSetBlendMode_wrapsetBlendMode:", "CGContextSetBlendMode_wrap", "void", &["proxy", "int"]),
    ("CGContextSetCharacterSpacingsetCharacterSpacing:", "CGContextSetCharacterSpacing", "void", &["proxy", "float"]),
    ("CGContextSetFillColorSpacesetFillColorSpace:", "CGContextSetFillColorSpace", "void", &["proxy", "proxy"]),
    ("CGContextSetFillColorWithColorsetFillColor:", "CGContextSetFillColorWithColor", "void", &["proxy", "proxy"]),
    ("CGContextSetFillColor_wrapsetFillColorX:Y:Z:Alpha:", "CGContextSetFillColor_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextSetFillPattern_wrapsetFillPattern:Red:Green:Blue:Alpha:", "CGContextSetFillPattern_wrap", "void", &["proxy", "proxy", "float", "float", "float", "float"]),
    ("CGContextSetFlatnesssetFlatness:", "CGContextSetFlatness", "void", &["proxy", "float"]),
    ("CGContextSetFontSizesetFontSize:", "CGContextSetFontSize", "void", &["proxy", "float"]),
    ("CGContextSetFontsetFont:", "CGContextSetFont", "void", &["proxy", "proxy"]),
    ("CGContextSetGrayFillColorsetGrayFillColorGray:Alpha:", "CGContextSetGrayFillColor", "void", &["proxy", "float", "float"]),
    ("CGContextSetGrayStrokeColorsetGrayStrokeColorGray:Alpha:", "CGContextSetGrayStrokeColor", "void", &["proxy", "float", "float"]),
    ("CGContextSetInterpolationQuality_wrapinterpolationQuality:", "CGContextSetInterpolationQuality_wrap", "void", &["proxy", "int"]),
    ("CGContextSetLineCap_wrapsetLineCap:", "CGContextSetLineCap_wrap", "void", &["proxy", "int"]),
    ("CGContextSetLineDash_wrapsetLineDashPhase:Lengths:", "CGContextSetLineDash_wrap", "void", &["proxy", "float", "oop"]),
    ("CGContextSetLineJoin_wrapsetLineJoin:", "CGContextSetLineJoin_wrap", "void", &["proxy", "int"]),
    ("CGContextSetLineWidthsetLineWidth:", "CGContextSetLineWidth", "void", &["proxy", "float"]),
    ("CGContextSetMiterLimitsetMiterLimit:", "CGContextSetMiterLimit", "void", &["proxy", "float"]),
    ("CGContextSetPatternPhase_wrapsetPatternPhaseWidth:Height:", "CGContextSetPatternPhase_wrap", "void", &["proxy", "float", "float"]),
    ("CGContextSetRGBFillColor_wrapsetFillColorRed:Green:Blue:Alpha:", "CGContextSetRGBFillColor_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextSetRGBStrokeColor_wrapsetStrokeColorRed:Green:Blue:Alpha:", "CGContextSetRGBStrokeColor_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextSetRenderingIntent_wrapsetRenderingIntent:", "CGContextSetRenderingIntent_wrap", "void", &["proxy", "unsigned_int"]),
    ("CGContextSetShadowWithColor_wrap2setShadowOffsetX:OffsetY:Blur:Red:Green:Blue:Alpha:", "CGContextSetShadowWithColor_wrap2", "void", &["proxy", "float", "float", "float", "float", "float", "float", "float"]),
    ("CGContextSetShadowWithColor_wrapsetShadowOffsetX:OffsetY:Blur:Color:", "CGContextSetShadowWithColor_wrap", "void", &["proxy", "float", "float", "float", "proxy"]),
    ("CGContextSetShadow_wrapsetShadowOffsetX:OffsetY:Blur:", "CGContextSetShadow_wrap", "void", &["proxy", "float", "float", "float"]),
    ("CGContextSetShouldAntialiassetShouldAntialias:", "CGContextSetShouldAntialias", "void", &["proxy", "bool"]),
    ("CGContextSetShouldSmoothFontssetShouldSmoothFonts:", "CGContextSetShouldSmoothFonts", "void", &["proxy", "bool"]),
    ("CGContextSetStrokeColorSpacesetStrokeColorSpace:", "CGContextSetStrokeColorSpace", "void", &["proxy", "proxy"]),
    ("CGContextSetStrokeColorWithColorsetStrokeColor:", "CGContextSetStrokeColorWithColor", "void", &["proxy", "proxy"]),
    ("CGContextSetStrokeColor_wrapsetStrokeColorX:Y:Z:Alpha:", "CGContextSetStrokeColor_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextSetStrokePattern_wrapsetStrokePattern:Red:Green:Blue:Alpha:", "CGContextSetStrokePattern_wrap", "void", &["proxy", "proxy", "float", "float", "float", "float"]),
    ("CGContextSetTextDrawingMode_wrapsetTextDrawingMode:", "CGContextSetTextDrawingMode_wrap", "void", &["proxy", "int"]),
    ("CGContextSetTextMatrix_wrapsetTextMatrix_A:B:C:D:TX:TY:", "CGContextSetTextMatrix_wrap", "void", &["proxy", "float", "float", "float", "float", "float", "float"]),
    ("CGContextSetTextPositionsetTextPositionX:Y:", "CGContextSetTextPosition", "void", &["proxy", "float", "float"]),
    ("CGContextShowTextAtPointshowTextAtX:Y:Text:", "CGContextShowTextAtPoint", "void", &["proxy", "float", "float", "cbv_len"]),
    ("CGContextShowTextshowText:", "CGContextShowText", "void", &["proxy", "bv_len"]),
    ("CGContextStrokeEllipseInRect_wrapstrokeEllipseX:Y:Width:Height:", "CGContextStrokeEllipseInRect_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextStrokePathstrokePath", "CGContextStrokePath", "void", &["proxy"]),
    ("CGContextStrokeRectWithWidth_wrapstrokeRectX:Y:Width:Height:StrokeWidth:", "CGContextStrokeRectWithWidth_wrap", "void", &["proxy", "float", "float", "float", "float", "float"]),
    ("CGContextStrokeRect_wrapstrokeRectX:Y:Width:Height:", "CGContextStrokeRect_wrap", "void", &["proxy", "float", "float", "float", "float"]),
    ("CGContextSynchronizesynchronize", "CGContextSynchronize", "void", &["proxy"]),
    ("CGContextTranslateCTMtranslateCTM_X:Y:", "CGContextTranslateCTM", "void", &["proxy", "float", "float"]),
    ("CGDataProviderCreateFromBVcreateForBytesResultProxy:", "CGDataProviderCreateFromBV", "proxy", &["cbv_len"]),
    ("CGDataProviderCreateFromURL_wrapcreateFromURLResultProxy:", "CGDataProviderCreateFromURL_wrap", "proxy", &["cbv_len"]),
    ("CGDataProviderGetTypeIDgetTypeID", "CGDataProviderGetTypeID", "unsigned_int", &[]),
    ("CGDataProviderReleaserelease", "CGDataProviderRelease", "void", &["proxy"]),
    ("CGDataProviderRetainretain", "CGDataProviderRetain", "void", &["proxy"]),
    ("CGDirectDisplayHeight_wrapgetHeight", "CGDirectDisplayHeight_wrap", "float", &["proxy"]),
    ("CGDirectDisplayWidth_wrapgetWidth", "CGDirectDisplayWidth_wrap", "float", &["proxy"]),
    ("CGDirectDisplayX_wrapgetX", "CGDirectDisplayX_wrap", "float", &["proxy"]),
    ("CGDirectDisplayY_wrapgetY", "CGDirectDisplayY_wrap", "float", &["proxy"]),
    ("CGDisplayHideCursorhideCursor", "CGDisplayHideCursor", "specific_success_int", &["proxy"]),
    ("CGDisplayMoveCursorToPoint_wrapmoveCursorToX:Y:", "CGDisplayMoveCursorToPoint_wrap", "specific_success_int", &["proxy", "float", "float"]),
    ("CGDisplayPixelsHighpixelHeight", "CGDisplayPixelsHigh", "int", &["proxy"]),
    ("CGDisplayPixelsWidepixelWidth", "CGDisplayPixelsWide", "int", &["proxy"]),
    ("CGDisplayShowCursorshowCursor", "CGDisplayShowCursor", "specific_success_int", &["proxy"]),
    ("CGFontCreateWithPlatformFont_wrapcreateIDResultProxy:", "CGFontCreateWithPlatformFont_wrap", "proxy", &["unsigned_int"]),
    ("CGFontReleaserelease", "CGFontRelease", "void", &["proxy"]),
    ("CGFontRetainretain", "CGFontRetain", "void", &["proxy"]),
    ("CGGetActiveDisplayAt_wrapgetActiveDisplayAtResultProxy:", "CGGetActiveDisplayAt_wrap", "proxy", &["unsigned_int"]),
    ("CGGetActiveDisplayCount_wrapgetActiveDisplayCount", "CGGetActiveDisplayCount_wrap", "unsigned_int", &[]),
    ("CGGetDisplayAt_wrapgetDisplayAtX:Y:Width:Height:ResultProxy:", "CGGetDisplayAt_wrap", "proxy", &["unsigned_int", "float", "float", "float", "float"]),
    ("CGGetDisplayCount_wrapgetDisplayCountXY:Width:Height:", "CGGetDisplayCount_wrap", "unsigned_int", &["float", "float", "float", "float"]),
    ("CGGetLastMouseDelta_xlastMouseDeltaX", "CGGetLastMouseDelta_x", "int", &[]),
    ("CGGetLastMouseDelta_ylastMouseDeltaY", "CGGetLastMouseDelta_y", "int", &[]),
    ("CGGetOnlineDisplayAt_wrapgetOnlineDisplayAtResultProxy:", "CGGetOnlineDisplayAt_wrap", "proxy", &["unsigned_int"]),
    ("CGGetOnlineDisplayCount_wrapgetOnlineDisplayCount", "CGGetOnlineDisplayCount_wrap", "unsigned_int", &[]),
    ("CGImageCreateCopyWithColorSpacecreateCopyWithColorSpace:ResultProxy:", "CGImageCreateCopyWithColorSpace", "proxy", &["proxy", "proxy"]),
    ("CGImageCreateCopycreateCopyResultProxy:", "CGImageCreateCopy", "proxy", &["proxy"]),
    ("CGImageCreateWithImageInRect_wrapcreateWithImageInRect_X:Y:Width:Height:ResultProxy:", "CGImageCreateWithImageInRect_wrap", "proxy", &["proxy", "float", "float", "float", "float"]),
    ("CGImageCreateWithJPEGDataProvider_wrapcreateWithJPEGDataProviderDecodeArray:ShouldInterpolate:ColorRenderingIntent:ResultProxy:", "CGImageCreateWithJPEGDataProvider_wrap", "proxy", &["proxy", "oop", "bool", "unsigned_int"]),
    ("CGImageCreateWithJPEGDataProvider_wrapcreateWithJPEGDataProviderShouldInterpolate:ColorRenderingIntent:ResultProxy:", "CGImageCreateWithJPEGDataProvider_wrap", "proxy", &["proxy", "bool", "unsigned_int"]),
    ("CGImageCreateWithMaskcreateWithMask:ResultProxy:", "CGImageCreateWithMask", "proxy", &["proxy", "proxy"]),
    ("CGImageCreateWithMaskingColors_wrapcreateWithMaskingColors_MinC1:MaxC1:MinC2:MaxC2:MinC3:MaxC3:MinC4:MaxC4:ResultProxy:", "CGImageCreateWithMaskingColors_wrap", "proxy", &["proxy", "float", "float", "float", "float", "float", "float", "float", "float"]),
    ("CGImageCreateWithPNGDataProvider_wrapcreateWithPNGDataProviderDecodeArray:ShouldInterpolate:ColorRenderingIntent:ResultProxy:", "CGImageCreateWithPNGDataProvider_wrap", "proxy", &["proxy", "oop", "bool", "unsigned_int"]),
    ("CGImageCreateWithPNGDataProvider_wrapcreateWithPNGDataProviderShouldInterpolate:ColorRenderingIntent:ResultProxy:", "CGImageCreateWithPNGDataProvider_wrap", "proxy", &["proxy", "bool", "unsigned_int"]),
    ("CGImageCreate_wrapcreateWidthHeight:BitsPerComponent:BitsPerPixel:BytesPerRow:ColorSpace:BitmapInfo:DataProvider:DecodeArray:ShouldInterpolate:ColorRenderingIntent:ResultProxy:", "CGImageCreate_wrap", "proxy", &["unsigned_int", "unsigned_int", "unsigned_int", "unsigned_int", "unsigned_int", "proxy", "unsigned_int", "proxy", "oop", "bool", "unsigned_int"]),
    ("CGImageCreate_wrapcreateWidthHeight:BitsPerComponent:BitsPerPixel:BytesPerRow:ColorSpace:BitmapInfo:DataProvider:ShouldInterpolate:ColorRenderingIntent:ResultProxy:", "CGImageCreate_wrap", "proxy", &["unsigned_int", "unsigned_int", "unsigned_int", "unsigned_int", "unsigned_int", "proxy", "unsigned_int", "proxy", "bool", "unsigned_int"]),
    ("CGImageGetAlphaInfoalphaInfo", "CGImageGetAlphaInfo", "unsigned_int", &["proxy"]),
    ("CGImageGetBitmapInfobitmapInfo", "CGImageGetBitmapInfo", "unsigned_int", &["proxy"]),
    ("CGImageGetBitsPerComponentbitsPerComponent", "CGImageGetBitsPerComponent", "unsigned_int", &["proxy"]),
    ("CGImageGetBitsPerPixelbitsPerPixel", "CGImageGetBitsPerPixel", "unsigned_int", &["proxy"]),
    ("CGImageGetBytesPerRowbytesPerRow", "CGImageGetBytesPerRow", "unsigned_int", &["proxy"]),
    ("CGImageGetColorSpacecolorSpaceResultProxy:", "CGImageGetColorSpace", "proxy", &["proxy"]),
    ("CGImageGetDataProviderdataProviderResultProxy:", "CGImageGetDataProvider", "proxy", &["proxy"]),
    ("CGImageGetHeightheight", "CGImageGetHeight", "unsigned_int", &["proxy"]),
    ("CGImageGetShouldInterpolategetShouldInterpolate", "CGImageGetShouldInterpolate", "bool", &["proxy"]),
    ("CGImageGetTypeIDtypeID", "CGImageGetTypeID", "unsigned_int", &[]),
    ("CGImageGetWidthwidth", "CGImageGetWidth", "unsigned_int", &["proxy"]),
    ("CGImageIsMaskisMask", "CGImageIsMask", "bool", &["proxy"]),
    ("CGImageMaskCreate_wrapcreateMaskWidthHeight:BitsPerComponent:BitsPerPixel:BytesPerRow:DataProvider:DecodeArray:ShouldInterpolate:ResultProxy:", "CGImageMaskCreate_wrap", "proxy", &["unsigned_int", "unsigned_int", "unsigned_int", "unsigned_int", "unsigned_int", "proxy", "oop", "bool"]),
    ("CGImageMaskCreate_wrapcreateMaskWidthHeight:BitsPerComponent:BitsPerPixel:BytesPerRow:DataProvider:ShouldInterpolate:ResultProxy:", "CGImageMaskCreate_wrap", "proxy", &["unsigned_int", "unsigned_int", "unsigned_int", "unsigned_int", "unsigned_int", "proxy", "bool"]),
    ("CGImageReleaserelease", "CGImageRelease", "void", &["proxy"]),
    ("CGImageRetainretain", "CGImageRetain", "void", &["proxy"]),
    ("CGImageSourceCreateImageAtIndex_wrapcreateImageAt:ResultProxy:", "CGImageSourceCreateImageAtIndex_wrap", "proxy", &["proxy", "unsigned_int"]),
    ("CGImageSourceCreateWithURL_wrapcreateWithURLResultProxy:", "CGImageSourceCreateWithURL_wrap", "proxy", &["cbv_len"]),
    ("CGImageSourceGetCountgetCount", "CGImageSourceGetCount", "unsigned_int", &["proxy"]),
    ("CGLayerCreateWithContext_wrapcreateWithContextWidth:Height:ResultProxy:", "CGLayerCreateWithContext_wrap", "proxy", &["proxy", "float", "float"]),
    ("CGLayerGetContextgetGCResultProxy:", "CGLayerGetContext", "proxy", &["proxy"]),
    ("CGLayerHeight_wrapheight", "CGLayerHeight_wrap", "float", &["proxy"]),
    ("CGLayerReleaserelease", "CGLayerRelease", "void", &["proxy"]),
    ("CGLayerRetainretain", "CGLayerRetain", "void", &["proxy"]),
    ("CGLayerWidth_wrapwidth", "CGLayerWidth_wrap", "float", &["proxy"]),
    ("CGMainDisplayIDmainResultProxy", "CGMainDisplayID", "proxy", &[]),
    ("CGReleaseAllDisplaysreleaseAll", "CGReleaseAllDisplays", "specific_success_int", &[]),
    ("ConnectionNumberconnectionNumber", "ConnectionNumber", "int", &["proxy"]),
    ("DefaultColormapOfScreendefaultColormapOfScreenResultProxy:", "DefaultColormapOfScreen", "proxy", &["proxy"]),
    ("DefaultDepthOfScreendefaultDepthOfScreen", "DefaultDepthOfScreen", "int", &["proxy"]),
    ("DefaultGCOfScreendefaultGCOfScreenResultProxy:", "DefaultGCOfScreen", "proxy", &["proxy"]),
    ("DefaultScreenOfDisplaydefaultScreenOfDisplayResultProxy:", "DefaultScreenOfDisplay", "proxy", &["proxy"]),
    ("DefaultScreendefaultScreen", "DefaultScreen", "int", &["proxy"]),
    ("DefaultVisualOfScreendefaultVisualOfScreenResultProxy:", "DefaultVisualOfScreen", "proxy", &["proxy"]),
    ("ExpandDir_primexpand", "ExpandDir_prim", "string", &["string"]),
    ("GetClipBoundingBoxHeight_wrapgetClipHeight", "GetClipBoundingBoxHeight_wrap", "float", &["proxy"]),
    ("GetClipBoundingBoxWidth_wrapgetClipWidth", "GetClipBoundingBoxWidth_wrap", "float", &["proxy"]),
    ("GetClipBoundingBoxX_wrapgetClipX", "GetClipBoundingBoxX_wrap", "float", &["proxy"]),
    ("GetClipBoundingBoxY_wrapgetClipY", "GetClipBoundingBoxY_wrap", "float", &["proxy"]),
    ("GetEventClass_wrapgetClass", "GetEventClass_wrap", "oop", &["proxy"]),
    ("GetEventKindgetKind", "GetEventKind", "unsigned_int", &["proxy"]),
    ("GetEventParam_BooleangetBooleanParam:Type:", "GetEventParam_Boolean", "unsigned_int", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventParam_CGContextRefgetContextParam:Type:ResultProxy:", "GetEventParam_CGContextRef", "proxy", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventParam_CGPointraw_getPointParam:", "GetEventParam_CGPoint", "oop", &["proxy", "cbv_len"]),
    ("GetEventParam_CGRectraw_getRectParam:", "GetEventParam_CGRect", "oop", &["proxy", "cbv_len"]),
    ("GetEventParam_CGSizeraw_getSizeParam:", "GetEventParam_CGSize", "oop", &["proxy", "cbv_len"]),
    ("GetEventParam_EventRefgetEventParam:Type:ResultProxy:", "GetEventParam_EventRef", "proxy", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventParam_GrafPtrgetGrafParam:Type:ResultProxy:", "GetEventParam_GrafPtr", "proxy", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventParam_WindowRefgetWindowParam:Type:ResultProxy:", "GetEventParam_WindowRef", "proxy", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventParam_int16getSignedShortParam:Type:", "GetEventParam_int16", "int", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventParam_int32getSignedParam:Type:", "GetEventParam_int32", "int", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventParam_uint16getUnsignedShortParam:Type:", "GetEventParam_uint16", "unsigned_int", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventParam_uint32getUnsignedParam:Type:", "GetEventParam_uint32", "unsigned_int", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventParam_uint8getUnsignedCharParam:Type:", "GetEventParam_uint8", "unsigned_int", &["proxy", "cbv_len", "cbv_len"]),
    ("GetEventTimegetSecondsSinceBoot", "GetEventTime", "float", &["proxy"]),
    ("GetWindowFromPortgetWindowResultProxy:", "GetWindowFromPort", "proxy", &["proxy"]),
    ("GetWindowPortBottomgetPortBottom", "GetWindowPortBottom", "int", &["proxy"]),
    ("GetWindowPortLeftgetPortLeft", "GetWindowPortLeft", "int", &["proxy"]),
    ("GetWindowPortRightgetPortRight", "GetWindowPortRight", "int", &["proxy"]),
    ("GetWindowPortTopgetPortTop", "GetWindowPortTop", "int", &["proxy"]),
    ("GetWindowPortgetPortResultProxy:", "GetWindowPort", "proxy", &["proxy"]),
    ("GetWindowRegion_wrapraw_getRegion:", "GetWindowRegion_wrap", "oop", &["proxy", "unsigned_short"]),
    ("GetWindowStructureWidths_wrapraw_getStructureWidths", "GetWindowStructureWidths_wrap", "oop", &["proxy"]),
    ("HeightOfScreenheightOfScreen", "HeightOfScreen", "int", &["proxy"]),
    ("IsValidWindowRefisValid", "IsValidWindowRef", "bool", &["proxy"]),
    ("IsWindowVisibleisVisible", "IsWindowVisible", "bool", &["proxy"]),
    ("MYSELFfileDescriptor", "MYSELF", "int", &["proxy_null"]),
    ("MYSELFsetFdResultProxy:", "MYSELF", "proxy_null", &["int"]),
    ("MYSELFwindowDescriptor", "MYSELF", "int", &["proxy_null"]),
    ("QDBeginCGContext_wrapbeginContextResultProxy:", "QDBeginCGContext_wrap", "proxy", &["proxy"]),
    ("QDEndCGContext_wrapendContext:", "QDEndCGContext_wrap", "void", &["proxy", "proxy"]),
    ("QuartzWindow__getPlatformWindowgetPlatformWindowResultProxy:", "QuartzWindow::getPlatformWindow", "proxy", &["proxy"]),
    ("QuartzWindow__get_scrap_textunmappedFetchFromClipboard", "QuartzWindow::get_scrap_text", "oop", &[]),
    ("QuartzWindow__put_scrap_textunmappedStoreToClipboard", "QuartzWindow::put_scrap_text", "specific_success_int", &["cbv_len"]),
    ("ReleaseEventrelease", "ReleaseEvent", "void", &["proxy"]),
    ("RootWindowOfScreenrootWindowOfScreenResultProxy:", "RootWindowOfScreen", "proxy", &["proxy"]),
    ("SelectWindowselect", "SelectWindow", "void", &["proxy"]),
    ("SendBehindsendBehind:", "SendBehind", "void", &["proxy", "proxy"]),
    ("SetMouseCoalescingEnabled_wrapsetMouseCoalescingEnabled", "SetMouseCoalescingEnabled_wrap", "specific_success_int", &["bool"]),
    ("SetPortWindowPortsetPortWindowPort", "SetPortWindowPort", "void", &["proxy"]),
    ("SetUserFocusWindowsetUserFocus", "SetUserFocusWindow", "specific_success_int", &["proxy"]),
    ("ShowWindowshow", "ShowWindow", "void", &["proxy"]),
    ("WhitePixelOfScreenwhitePixelOfScreen", "WhitePixelOfScreen", "long", &["proxy"]),
    ("WidthMMOfScreenwidthMMOfScreen", "WidthMMOfScreen", "int", &["proxy"]),
    ("WidthOfScreenwidthOfScreen", "WidthOfScreen", "int", &["proxy"]),
    ("XAllocColorCells_wrapxAllocColorCellsInColormap:Contig:PlaneMasksReturn:PixelsReturn:", "XAllocColorCells_wrap", "void", &["proxy", "proxy", "bool", "oop", "oop"]),
    ("XAllocColorxAllocColorInColormap:Color:", "XAllocColor", "int", &["proxy", "proxy", "proxy"]),
    ("XAllocSizeHintsnewResultProxy", "XAllocSizeHints", "proxy", &[]),
    ("XAllocWMHintsnewResultProxy", "XAllocWMHints", "proxy", &[]),
    ("XBellxBell:", "XBell", "void", &["proxy", "int"]),
    ("XChangeGCxChangeGC:ValueMask:Values:", "XChangeGC", "void", &["proxy", "proxy", "unsigned_long", "proxy"]),
    ("XChangeWindowAttributes_wrapxChangeWindowAttributesIn:Attributes:", "XChangeWindowAttributes_wrap", "void", &["proxy", "proxy", "proxy"]),
    ("XCheckMaskEventxCheckMask:OfEvent:", "XCheckMaskEvent", "bool", &["proxy", "long", "proxy"]),
    ("XCheckTypedEventxCheckType:OfEvent:", "XCheckTypedEvent", "bool", &["proxy", "int", "proxy"]),
    ("XCirculateSubwindowsDownxCirculateSubwindowsDown:", "XCirculateSubwindowsDown", "void", &["proxy", "proxy"]),
    ("XCirculateSubwindowsUpxCirculateSubwindowsUp:", "XCirculateSubwindowsUp", "void", &["proxy", "proxy"]),
    ("XCirculateSubwindowsxCirculateSubwindows:Direction:", "XCirculateSubwindows", "void", &["proxy", "proxy", "int"]),
    ("XClearAreaxClearAreaIn:X:Y:Width:Height:Exposures:", "XClearArea", "void", &["proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int", "bool"]),
    ("XClientMessageEvent_atomAt_wrapatomAt:ResultProxy:", "XClientMessageEvent_atomAt_wrap", "proxy", &["proxy", "unsigned_int"]),
    ("XCopyAreaxCopyAreaSrc:Dest:GC:SrcX:SrcY:Width:Height:DestX:DestY:", "XCopyArea", "void", &["proxy", "proxy", "proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int", "int", "int"]),
    ("XCreateBitmapFromDataxCreateBitmapDrawable:Data:Width:Height:ResultProxy:", "XCreateBitmapFromData", "proxy", &["proxy", "proxy", "cbv", "unsigned_int", "unsigned_int"]),
    ("XCreateColormapxCreateColormapWindow:Visual:Allocate:ResultProxy:", "XCreateColormap", "proxy", &["proxy", "proxy", "proxy", "bool"]),
    ("XCreateFontCursorxCreateFontCursorType:ResultProxy:", "XCreateFontCursor", "proxy", &["proxy", "int"]),
    ("XCreateGCxCreateGCDrawable:ValueMask:Values:ResultProxy:", "XCreateGC", "proxy", &["proxy", "proxy", "unsigned_long", "proxy"]),
    ("XCreateIOWindow_wrapxCreateIOWindowIn:X:Y:Width:Height:Depth:Visual:Attributes:ResultProxy:", "XCreateIOWindow_wrap", "proxy", &["proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int", "int", "proxy", "proxy"]),
    ("XCreateImage_wrapxCreateImage:Depth:Format:Width:Height:BitmapPad:ResultProxy:", "XCreateImage_wrap", "proxy", &["proxy", "proxy", "unsigned_int", "int", "unsigned_int", "unsigned_int", "int"]),
    ("XCreatePixmapCursorxCreatePixmapCursorSource:Mask:ForegroundColor:BackgroundColor:X:Y:ResultProxy:", "XCreatePixmapCursor", "proxy", &["proxy", "proxy", "proxy_null", "proxy", "proxy", "unsigned_int", "unsigned_int"]),
    ("XCreatePixmapxCreatePixmap:Width:Height:Depth:ResultProxy:", "XCreatePixmap", "proxy", &["proxy", "proxy", "unsigned_int", "unsigned_int", "unsigned_int"]),
    ("XCreateRegion_wrapxCreateRegionResultProxy", "XCreateRegion_wrap", "proxy", &[]),
    ("XCreateSimpleWindowxCreateSimpleWindowIn:X:Y:Width:Height:BorderWidth:Border:Background:ResultProxy:", "XCreateSimpleWindow", "proxy", &["proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int", "unsigned_int", "long", "long"]),
    ("XDefineCursorxDefineCursorWindow:Cursor:", "XDefineCursor", "void", &["proxy", "proxy", "proxy_null"]),
    ("XDestroyImagexDestroyImage", "XDestroyImage", "void", &["proxy"]),
    ("XDestroyRegion_wrapxDestroyRegion", "XDestroyRegion_wrap", "void", &["proxy"]),
    ("XDestroySubwindowsxDestroySubwindows:", "XDestroySubwindows", "void", &["proxy", "proxy"]),
    ("XDestroyWindowxDestroyWindow:", "XDestroyWindow", "void", &["proxy", "proxy"]),
    ("XDisplayNamexDisplayName", "XDisplayName", "string", &["string"]),
    ("XDrawArcxDrawArc:GC:X:Y:Width:Height:StartAngle:EndAngle:", "XDrawArc", "void", &["proxy", "proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int", "int", "int"]),
    ("XDrawLines_wrapxDrawLines:GC:Xs:Ys:Mode:", "XDrawLines_wrap", "void", &["proxy", "proxy", "proxy", "oop", "oop", "int"]),
    ("XDrawLinexDrawLine:GC:X1:Y1:X2:Y2:", "XDrawLine", "void", &["proxy", "proxy", "proxy", "int", "int", "int", "int"]),
    ("XDrawPointxDrawPoint:GC:X:Y:", "XDrawPoint", "void", &["proxy", "proxy", "proxy", "int", "int"]),
    ("XDrawRectanglexDrawRectangle:GC:X:Y:Width:Height:", "XDrawRectangle", "void", &["proxy", "proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int"]),
    ("XDrawString16_wrapxDrawString16:GC:X:Y:StringVector:", "XDrawString16_wrap", "void", &["proxy", "proxy", "proxy", "int", "int", "oop"]),
    ("XDrawStringxDrawString:GC:X:Y:String:", "XDrawString", "void", &["proxy", "proxy", "proxy", "int", "int", "string_len_null"]),
    ("XEmptyRegion_wrapxEmptyRegion", "XEmptyRegion_wrap", "bool", &["proxy"]),
    ("XEqualRegion_wrapxEqualRegion:", "XEqualRegion_wrap", "bool", &["proxy", "proxy"]),
    ("XEventsQueuedxEventsQueued:", "XEventsQueued", "int", &["proxy", "int"]),
    ("XFetchBytes_wrapxFetchBytes", "XFetchBytes_wrap", "string", &["proxy"]),
    ("XFillArcxFillArc:GC:X:Y:Width:Height:StartAngle:EndAngle:", "XFillArc", "void", &["proxy", "proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int", "int", "int"]),
    ("XFillPolygon_wrapxFillPolygon:GC:Xs:Ys:Shape:Mode:", "XFillPolygon_wrap", "void", &["proxy", "proxy", "proxy", "oop", "oop", "int", "int"]),
    ("XFillRectanglexFillRectangle:GC:X:Y:Width:Height:", "XFillRectangle", "void", &["proxy", "proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int"]),
    ("XFlushxFlush", "XFlush", "void", &["proxy"]),
    ("XFreeColorCells_wrapxFreeColorCellsInColormap:Pixels:Planes:", "XFreeColorCells_wrap", "void", &["proxy", "proxy", "oop", "unsigned_long"]),
    ("XFreeColormapxFreeColormap:", "XFreeColormap", "void", &["proxy", "proxy"]),
    ("XFreeCursorxFreeCursor:", "XFreeCursor", "void", &["proxy", "proxy"]),
    ("XFreeFontxFreeFont:", "XFreeFont", "void", &["proxy", "proxy"]),
    ("XFreeGCxFreeGC:", "XFreeGC", "void", &["proxy", "proxy"]),
    ("XFreePixmapxFreePixmap:", "XFreePixmap", "void", &["proxy", "proxy"]),
    ("XFree_XSizeHints_wrapdelete", "XFree_XSizeHints_wrap", "void", &["proxy"]),
    ("XFree_XWMHints_wrapdelete", "XFree_XWMHints_wrap", "void", &["proxy"]),
    ("XFreefreeValue", "XFree", "void", &["proxy"]),
    ("XGetGCValues_wrapxGetGCValuesGC:ValueMask:Values:", "XGetGCValues_wrap", "void", &["proxy", "proxy", "unsigned_long", "proxy"]),
    ("XGetImagexGetImage:X:Y:Width:Height:PlaneMask:Format:ResultProxy:", "XGetImage", "proxy", &["proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int", "unsigned_long", "int"]),
    ("XGetPixelxGetPixelX:Y:", "XGetPixel", "unsigned_long", &["proxy", "int", "int"]),
    ("XGetSubImagexGetSubImage:X:Y:Width:Height:PlaneMask:Format:DestImage:DestX:DestY:ResultProxy:", "XGetSubImage", "proxy", &["proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int", "unsigned_long", "int", "proxy", "int", "int"]),
    ("XGetWindowAttributes_wrapxGetWindowAttributesIn:ResultProxy:", "XGetWindowAttributes_wrap", "proxy", &["proxy", "proxy"]),
    ("XGrabPointerxGrabPointerWindow:OwnerEvents:EventMask:PointerMode:KeyboardMode:ConfineTo:Cursor:Time:", "XGrabPointer", "int", &["proxy", "proxy", "bool", "unsigned_int", "int", "int", "proxy_null", "proxy_null", "unsigned_long"]),
    ("XImageGetData_wrapxImageGetData:", "XImageGetData_wrap", "void", &["proxy", "bv_len"]),
    ("XImagePutData_wrapxImagePutData:MappedBy:", "XImagePutData_wrap", "void", &["proxy", "bv_len", "oop"]),
    ("XInternAtomxInternAtom:OnlyIfExists:ResultProxy:", "XInternAtom", "proxy", &["proxy", "string", "bool"]),
    ("XIntersectRegion_wrapxIntersectRegion:Region:", "XIntersectRegion_wrap", "void", &["proxy", "proxy", "proxy"]),
    ("XLoadQueryFont_wrapxLoadQueryFont:ResultProxy:", "XLoadQueryFont_wrap", "proxy", &["proxy", "string_null"]),
    ("XLookupString_wrapxLookupStringReturn:KeySymReturn:", "XLookupString_wrap", "int", &["proxy", "bv_len", "oop"]),
    ("XLowerWindowxLowerWindow:", "XLowerWindow", "void", &["proxy", "proxy"]),
    ("XMapSubwindowsxMapSubwindows:", "XMapSubwindows", "void", &["proxy", "proxy"]),
    ("XMapWindowxMapWindow:", "XMapWindow", "void", &["proxy", "proxy"]),
    ("XMatchVisualInfo_wrapxMatchVisualInfoScreen:Depth:Class:ResultProxy:", "XMatchVisualInfo_wrap", "proxy", &["proxy", "int", "int", "int"]),
    ("XMoveResizeWindowxMoveResizeWindow:X:Y:W:H:", "XMoveResizeWindow", "void", &["proxy", "proxy", "int", "int", "int", "int"]),
    ("XMoveWindowBy_wrapxMoveWindow:ByX:Y:", "XMoveWindowBy_wrap", "void", &["proxy", "proxy", "int", "int"]),
    ("XMoveWindowBy_wrapxMoveWindowBy:X:Y:", "XMoveWindowBy_wrap", "void", &["proxy", "proxy", "int", "int"]),
    ("XMoveWindowxMoveWindow:X:Y:", "XMoveWindow", "void", &["proxy", "proxy", "int", "int"]),
    ("XNextEvent_wrapxNextEventPeek:Protos:", "XNextEvent_wrap", "oop", &["proxy", "bool", "oop"]),
    ("XNextEventxNextEventInto:", "XNextEvent", "void", &["proxy", "proxy"]),
    ("XOffsetRegion_wrapxOffsetX:Y:", "XOffsetRegion_wrap", "void", &["proxy", "int", "int"]),
    ("XPeekEventxPeekEventInto:", "XPeekEvent", "void", &["proxy", "proxy"]),
    ("XPendingxPending", "XPending", "int", &["proxy"]),
    ("XPutBackEventxPutBackEvent:", "XPutBackEvent", "void", &["proxy", "proxy"]),
    ("XPutImagexPutImage:GC:Image:SrcX:SrcY:DestX:DestY:Width:Height:", "XPutImage", "void", &["proxy", "proxy", "proxy", "proxy", "int", "int", "int", "int", "unsigned_int", "unsigned_int"]),
    ("XPutPixelxPutPixelX:Y:Value:", "XPutPixel", "void", &["proxy", "int", "int", "unsigned_long"]),
    ("XQueryBestStippleHeightxQueryBestStippleHeight:Width:Height:", "XQueryBestStippleHeight", "unsigned_long", &["proxy", "proxy", "int", "int"]),
    ("XQueryBestStippleWidthxQueryBestStippleWidth:Width:Height:", "XQueryBestStippleWidth", "unsigned_long", &["proxy", "proxy", "int", "int"]),
    ("XQueryBestTileHeightxQueryBestTileHeight:Width:Height:", "XQueryBestTileHeight", "unsigned_long", &["proxy", "proxy", "int", "int"]),
    ("XQueryBestTileWidthxQueryBestTileWidth:Width:Height:", "XQueryBestTileWidth", "unsigned_long", &["proxy", "proxy", "int", "int"]),
    ("XQueryColors_wrapxQueryColorsInColormap:Colors:", "XQueryColors_wrap", "void", &["proxy", "proxy", "oop"]),
    ("XQueryColorxQueryColorInColormap:Color:", "XQueryColor", "void", &["proxy", "proxy", "proxy"]),
    ("XQueryFontxQueryFont:ResultProxy:", "XQueryFont", "proxy", &["proxy", "proxy"]),
    ("XRaiseWindowxRaiseWindow:", "XRaiseWindow", "void", &["proxy", "proxy"]),
    ("XScreenNumberOfScreenxScreenNumberOfScreen", "XScreenNumberOfScreen", "int", &["proxy"]),
    ("XSelectInputxSelectInputOfWindow:EventMask:", "XSelectInput", "void", &["proxy", "proxy", "long"]),
    ("XServerVendorxServerVendor", "XServerVendor", "string", &["proxy"]),
    ("XSetBackgroundxSetGC:Background:", "XSetBackground", "void", &["proxy", "proxy", "unsigned_long"]),
    ("XSetClipMaskxSetClipMask:Pixmap:", "XSetClipMask", "void", &["proxy", "proxy", "proxy_null"]),
    ("XSetClipOriginxSetClipOrigin:X:Y:", "XSetClipOrigin", "void", &["proxy", "proxy", "int", "int"]),
    ("XSetClipRectangle_wrapxSetClipRectangle:X:Y:Width:Height:", "XSetClipRectangle_wrap", "void", &["proxy", "proxy", "int", "int", "int", "int"]),
    ("XSetDashesxSetGC:DashesOffset:DashList:", "XSetDashes", "void", &["proxy", "proxy", "int", "bv_len"]),
    ("XSetFillRulexSetGC:FillRule:", "XSetFillRule", "void", &["proxy", "proxy", "int"]),
    ("XSetFillStylexSetGC:FillStyle:", "XSetFillStyle", "void", &["proxy", "proxy", "int"]),
    ("XSetFontxSetGC:Font:", "XSetFont", "void", &["proxy", "proxy", "proxy"]),
    ("XSetForegroundxSetGC:Foreground:", "XSetForeground", "void", &["proxy", "proxy", "unsigned_long"]),
    ("XSetFunctionxSetGC:Function:", "XSetFunction", "void", &["proxy", "proxy", "int"]),
    ("XSetGraphicsExposuresxSetGC:GraphicsExposures:", "XSetGraphicsExposures", "void", &["proxy", "proxy", "bool"]),
    ("XSetInputFocusxSetInputFocusWindow:RevertTo:Time:", "XSetInputFocus", "void", &["proxy", "proxy", "int", "int"]),
    ("XSetLineAttributesxSetGC:LineAttributesWidth:LineStyle:CapStyle:JoinStyle:", "XSetLineAttributes", "void", &["proxy", "proxy", "unsigned_int", "int", "int", "int"]),
    ("XSetPlaneMaskxSetGC:PlaneMask:", "XSetPlaneMask", "void", &["proxy", "proxy", "unsigned_long"]),
    ("XSetStipplexSetGC:Stipple:", "XSetStipple", "void", &["proxy", "proxy", "proxy"]),
    ("XSetSubwindowModexSetGC:SubwindowMode:", "XSetSubwindowMode", "void", &["proxy", "proxy", "int"]),
    ("XSetTilexSetGC:Tile:", "XSetTile", "void", &["proxy", "proxy", "proxy"]),
    ("XSetWMHintsxSetWMHintsOfWindow:To:", "XSetWMHints", "void", &["proxy", "proxy", "proxy"]),
    ("XSetWMIconNamexSetWMIconNameOfWindow:To:", "XSetWMIconName", "void", &["proxy", "proxy", "proxy"]),
    ("XSetWMNamexSetWMNameOfWindow:To:", "XSetWMName", "void", &["proxy", "proxy", "proxy"]),
    ("XSetWMNormalHintsxSetWMNormalHintsOfWindow:To:", "XSetWMNormalHints", "void", &["proxy", "proxy", "proxy"]),
    ("XSetWMProtocol_wrapxSetWMProtocolOfWindow:Protocol:", "XSetWMProtocol_wrap", "int", &["proxy", "proxy", "proxy"]),
    ("XSetWindowColormapxSetWindow:Colormap:", "XSetWindowColormap", "void", &["proxy", "proxy", "proxy"]),
    ("XShapeCombineMask_wrapxShapeCombineMask:DestKind:X:Y:Mask:Operation:", "XShapeCombineMask_wrap", "void", &["proxy", "proxy", "int", "int", "int", "proxy_null", "int"]),
    ("XShapeCombineRectangle_wrapxShapeCombineRectangle:DestKind:X:Y:Width:Height:Operation:", "XShapeCombineRectangle_wrap", "void", &["proxy", "proxy", "int", "int", "int", "unsigned_int", "unsigned_int", "int"]),
    ("XShapeCombineRegion_wrapxShapeCombineRegion:DestKind:X:Y:Region:Operation:", "XShapeCombineRegion_wrap", "void", &["proxy", "proxy", "int", "int", "int", "proxy", "int"]),
    ("XShapeCombineShape_wrapxShapeCombineShape:DestKind:X:Y:Shape:ShapeKind:Operation:", "XShapeCombineShape_wrap", "void", &["proxy", "proxy", "int", "int", "int", "proxy", "int", "int"]),
    ("XShapeQueryExtension_wrapxShapeQueryExtension", "XShapeQueryExtension_wrap", "bool", &["proxy"]),
    ("XStoreBytes_wrapxStoreBytes:", "XStoreBytes_wrap", "void", &["proxy", "string"]),
    ("XStoreColors_wrapxStoreColorsInColormap:Colors:", "XStoreColors_wrap", "void", &["proxy", "proxy", "oop"]),
    ("XStoreColorxStoreColorInColormap:Color:", "XStoreColor", "void", &["proxy", "proxy", "proxy"]),
    ("XStringToTextProperty_wrapxStringToTextProperty:", "XStringToTextProperty_wrap", "int", &["proxy", "string"]),
    ("XSubImagexSubImageX:Y:Width:Height:ResultProxy:", "XSubImage", "proxy", &["proxy", "int", "int", "unsigned_int", "unsigned_int"]),
    ("XSubtractRegion_wrapxSubtractRegion:Region:", "XSubtractRegion_wrap", "void", &["proxy", "proxy", "proxy"]),
    ("XSynchronizexSynchronize:", "XSynchronize", "void", &["proxy", "bool"]),
    ("XSyncxSyncDiscardingIf:", "XSync", "void", &["proxy", "bool"]),
    ("XTextWidthxTextWidth:", "XTextWidth", "int", &["proxy", "string_len_null"]),
    ("XTranslateCoordinates_wrapxTranslateCoordinatesSrcWindow:DstWindow:Coordinates:ResultProxy:", "XTranslateCoordinates_wrap", "proxy_null", &["proxy", "proxy", "proxy", "oop"]),
    ("XUndefineCursorxUndefineCursorWindow:", "XUndefineCursor", "void", &["proxy", "proxy"]),
    ("XUngrabButtonxUngrabButton:Modifiers:Window:", "XUngrabButton", "void", &["proxy", "int", "int", "proxy"]),
    ("XUngrabPointerxUngrabPointerTime:", "XUngrabPointer", "void", &["proxy", "unsigned_long"]),
    ("XUnionRectWithRegion_wrapxUnionRectWithRegion:X:Y:Width:Height:", "XUnionRectWithRegion_wrap", "void", &["proxy", "proxy", "int", "int", "unsigned_int", "unsigned_int"]),
    ("XUnionRegion_wrapxUnionRegion:Region:", "XUnionRegion_wrap", "void", &["proxy", "proxy", "proxy"]),
    ("XUnmapSubwindowsxUnmapSubwindows:", "XUnmapSubwindows", "void", &["proxy", "proxy"]),
    ("XUnmapWindowxUnmapWindow:", "XUnmapWindow", "void", &["proxy", "proxy"]),
    ("XVendorReleasexVendorRelease", "XVendorRelease", "int", &["proxy"]),
    ("XVisualIDFromVisualxVisualIDFromVisual", "XVisualIDFromVisual", "int", &["proxy"]),
    ("XWarpPointerxWarpPointerSrcWindow:DestWindow:SrcX:SrcY:SrcWidth:SrcHeight:DestX:DestY:", "XWarpPointer", "void", &["proxy", "proxy_null", "proxy_null", "int", "int", "unsigned_int", "unsigned_int", "int", "int"]),
    ("XXorRegion_wrapxXorRegion:Region:", "XXorRegion_wrap", "void", &["proxy", "proxy", "proxy"]),
    ("XftColorAllocValuexftColorAllocValue:Colormap:RenderColor:XftColor:", "XftColorAllocValue", "bool", &["proxy", "proxy", "proxy", "proxy", "proxy"]),
    ("XftDrawCreatexftDrawCreate:Visual:Colormap:ResultProxy:", "XftDrawCreate", "proxy", &["proxy", "proxy", "proxy", "proxy"]),
    ("XftDrawString8_wrapxftDrawString8:Font:X:Y:String:", "XftDrawString8_wrap", "void", &["proxy", "proxy", "proxy", "int", "int", "string_len_null"]),
    ("XftFontOpenNamexftFontOpenNameOnScreen:Name:ResultProxy:", "XftFontOpenName", "proxy", &["proxy", "int", "string"]),
    ("XftTextExtents8_wrapxftTextExtents8:String:Extents:", "XftTextExtents8_wrap", "void", &["proxy", "proxy", "string_len_null", "proxy"]),
    ("accept_wrapbasicAcceptSocketInfo:ResultProxy:", "accept_wrap", "proxy_or_errno", &["proxy_null", "oop"]),
    ("acosarcCos", "acos", "float", &["float"]),
    ("acosharcCosh", "acosh", "float", &["float"]),
    ("asinarcSin", "asin", "float", &["float"]),
    ("asinharcSinh", "asinh", "float", &["float"]),
    ("atan2arcTan:", "atan2", "float", &["float", "float"]),
    ("atanarcTan", "atan", "float", &["float"]),
    ("atanharcTanh", "atanh", "float", &["float"]),
    ("bind_wrapbasicBindSocketFamily:Port:Address:", "bind_wrap", "int_or_errno", &["proxy_null", "short", "unsigned_short", "cbv_len"]),
    ("close_wrapbasicCloseFile", "close_wrap", "int_or_errno", &["proxy_null"]),
    ("connect_wrapbasicConnectSocketFamily:Port:Address:", "connect_wrap", "int_or_errno", &["proxy_null", "short", "unsigned_short", "cbv_len"]),
    ("cos", "cos", "float", &["float"]),
    ("cosh", "cosh", "float", &["float"]),
    ("exp", "exp", "float", &["float"]),
    ("fcntlbasicFcntlFileRequest:Arg:", "fcntl", "int_or_errno", &["proxy_null", "int", "int"]),
    ("fstat_wrapperfstatResultProxy:", "fstat_wrapper", "proxy", &["proxy_null"]),
    ("getcwd_wrapgetcwd", "getcwd_wrap", "string", &[]),
    ("getenvenvironmentAt", "getenv", "string", &["string"]),
    ("gethostbyaddr_wrapbasicGetHostByAddrType:", "gethostbyaddr_wrap", "string", &["cbv_len", "int"]),
    ("gethostbyname_wrapbasicGetHostByName", "gethostbyname_wrap", "oop", &["string"]),
    ("getpid", "getpid", "int", &[]),
    ("listenbasicListenSocketBacklog:", "listen", "int_or_errno", &["proxy_null", "int"]),
    ("log10base10Log", "log10", "float", &["float"]),
    ("log2base2Log", "log2", "float", &["float"]),
    ("lognaturalLog", "log", "float", &["float"]),
    ("lseekbasicLseekFileOffset:Whence:", "lseek", "int_or_errno", &["proxy_null", "int", "int"]),
    ("lstat_wrapperlstatResultProxy:", "lstat_wrapper", "proxy", &["string"]),
    ("maxAscent", "maxAscent", "int", &["proxy"]),
    ("maxCharWidth", "maxCharWidth", "int", &["proxy"]),
    ("maxDescent", "maxDescent", "int", &["proxy"]),
    ("open_wrapbasicOpenFileNameFlags:Mode:ResultProxy:", "open_wrap", "proxy_or_errno", &["string", "int", "int"]),
    ("perCharWidth:", "perCharWidth", "int", &["proxy", "int"]),
    ("powraisedTo:", "pow", "float", &["float", "float"]),
    ("putenv_wrapenvironmentAtPut:", "putenv_wrap", "int", &["string", "string"]),
    ("read_wrapbasicReadFileInto:Offset:Count:", "read_wrap", "int_or_errno", &["proxy_null", "bv_len", "int", "int"]),
    ("s_isblk_wrappers_isblk", "s_isblk_wrapper", "bool", &["proxy"]),
    ("s_ischr_wrappers_ischr", "s_ischr_wrapper", "bool", &["proxy"]),
    ("s_isdir_wrappers_isdir", "s_isdir_wrapper", "bool", &["proxy"]),
    ("s_isfifo_wrappers_isfifo", "s_isfifo_wrapper", "bool", &["proxy"]),
    ("s_islnk_wrappers_islnk", "s_islnk_wrapper", "bool", &["proxy"]),
    ("s_isreg_wrappers_isreg", "s_isreg_wrapper", "bool", &["proxy"]),
    ("s_issock_wrappers_issock", "s_issock_wrapper", "bool", &["proxy"]),
    ("select_read_wrapbasicSelectReadIntoSize:", "select_read_wrap", "int", &["oop", "int"]),
    ("select_wrapbasicSelectIntoSize:", "select_wrap", "int", &["oop", "int"]),
    ("setsockoptLevel:OptName:OptVal:", "setsockopt", "int_or_errno", &["proxy_null", "int", "int", "cbv_len_null"]),
    ("sin", "sin", "float", &["float"]),
    ("sinh", "sinh", "float", &["float"]),
    ("socket_wrapbasicSocketDomainType:Protocol:ResultProxy:", "socket_wrap", "proxy_or_errno", &["int", "int", "int"]),
    ("sqrtsquareRoot", "sqrt", "float", &["float"]),
    ("stat_st_atime_wrapperst_atime", "stat_st_atime_wrapper", "oop", &["proxy"]),
    ("stat_st_ctime_wrapperst_ctime", "stat_st_ctime_wrapper", "oop", &["proxy"]),
    ("stat_st_mtime_wrapperst_mtime", "stat_st_mtime_wrapper", "oop", &["proxy"]),
    ("stat_wrapperstatResultProxy:", "stat_wrapper", "proxy", &["string"]),
    ("system_wrapcommand", "system_wrap", "int", &["string"]),
    ("tan", "tan", "float", &["float"]),
    ("tanh", "tanh", "float", &["float"]),
    ("tgetenv_wrapperprimGetenv", "tgetenv_wrapper", "string", &["string"]),
    ("tgetflaggetflag", "tgetflag", "bool", &["string"]),
    ("tgetnumgetnum", "tgetnum", "int_or_errno", &["string"]),
    ("tgetstr_wrappergetstr", "tgetstr_wrapper", "string", &["string"]),
    ("tgoto_wrappergotoCol:Row:", "tgoto_wrapper", "string", &["string", "int", "int"]),
    ("unlinkbasicUnlink", "unlink", "int_or_errno", &["string"]),
    ("write_wrapbasicWriteFileInto:Offset:Count:", "write_wrap", "int_or_errno", &["proxy_null", "cbv_len", "int", "int"]),
    ("xButtonEvent_timerawTime", "xButtonEvent_time", "oop", &["proxy"]),
    ("xCrossingEvent_timerawTime", "xCrossingEvent_time", "oop", &["proxy"]),
    ("xKeyEvent_timerawTime", "xKeyEvent_time", "oop", &["proxy"]),
    ("xMotionEvent_timerawTime", "xMotionEvent_time", "oop", &["proxy"]),
];
